SIMPLE_SETTINGS = {
    "OVERRIDE_BY_ENV": True,
    "REQUIRED_SETTINGS": ("KAFKA_BOOTSTRAP_SERVER",),
}

# The following variables can be ovirriden from ENV
KAFKA_BOOTSTRAP_SERVER = "kafka://kafka:9092"
SCHEMA_REGISTRY_URL = "http://schema-registry:8081"

CHECK_FOR_NEW_TRANSACTIONS_PERIOD = 2
WINDOW_SECONDS_SIZE = 30 * 60
BOT_DETECTION_THRESHOLD = 10
WEB3_HTTP_PROVIDER = ""
FCM_API_KEY = ""
POSTGRES_DB = "postgres"
POSTGRES_USER = "postgres"
POSTGRES_PASSWORD = ""
POSTGRES_HOST = "db"
SECONDS_TO_SEND_REMINDER_NOTIFICATION = 10 * 60
